"""Generate user-facing configuration from the runtime registry."""

from .settings import FIELDS, PRODUCTION_REQUIRED, string_value


def catalog():
    return [
        {
            "key": "HOMESERVER_" + name.upper(),
            "type": field.kind,
            "default": "" if field.secret else field.default,
            "unit": field.unit,
            "secret": field.secret,
            "required_production": name in PRODUCTION_REQUIRED,
            "consumer": field.consumer,
            "application": field.application,
            "choices": field.choices,
        }
        for name, field in FIELDS.items()
    ]


def example_env():
    import json

    lines = ["# Generated by homeserver config catalog; no production credentials."]
    for name, field in FIELDS.items():
        value = (
            ("[]" if field.kind == "json" else "")
            if field.secret
            else (
                json.dumps(field.default) if field.kind == "json" else string_value(field.default)
            )
        )
        lines += [
            f"# {field.kind}; {field.unit or 'unitless'}; consumer={field.consumer}; "
            f"apply={field.application}",
            "HOMESERVER_" + name.upper() + "=" + json.dumps(value, ensure_ascii=False),
        ]
    return "\n".join(lines) + "\n"
